decrypt:
  rubygems.yml: repo/rubygems.yml.asc
assets:
  s3cfg: yegor256/home#assets/s3cfg
install: |
  sudo bundle install
  sudo apt-get install -y bcrypt
release:
  script: |-
    rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/rultor/version.rb
    gem build rultor.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
    sudo gem install pdd
    pdd --source=$(pwd) --verbose --file=rultor-remote.xml
    s3cmd --no-progress put rultor-remote.xml --config=../s3cfg s3://pdd.teamed.io/rltor-remote.xml
architect:
- yegor256
- alex-palevsky
merge:
  commanders:
  - caarlos0
  - carlosmiranda
  - darkled
  - dmzaytsev
  - ggajos
  - krzyk
  - longtimeago
  - pinaf
deploy:
  commanders:
  - yegor256