version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
install:
  - cmd: ruby --version
build_script:
  - bundle install
test_script:
  - rake
